/*
 * @Descripttion: 
 * @version: 
 * @Author: wushide
 * @Date: 2023-09-21 08:21:55
 * @LastEditors: wushide
 * @LastEditTime: 2023-09-21 11:28:41
 */
import "./globals.css"

import type { Metadata } from "next"
import { Inter } from "next/font/google"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
